project_id = "tlp-presenca-operacional"

[functions.delete-old-photos]
verify_jwt = false

[functions.checkin-publico]
verify_jwt = false

[functions.marcacao-publica]
verify_jwt = false

[functions.validar-colaborador]
verify_jwt = false

[functions.admin-criar-usuario]
verify_jwt = true

[functions.admin-redefinir-senha]
verify_jwt = true
